name: Selenium Test Suite

on:
  # Manual trigger for workflow dispatch
  workflow_dispatch:
    inputs:
      run_mode:
        description: 'Select which tests to run'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - stock_comparison

  # Scheduled trigger for nightly runs
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest

    - name: Download WebDriver (ChromeDriver)
      run: |
        sudo apt-get install -y chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Run Tests Based on Input
      run: |
        if [ "${{ github.event.inputs.run_mode }}" == "full" ]; then
          pytest pytestAssignmentGoogleFinance/test_stockComparison.py pytestAssignmentGoogleFinance/test_titleCheck.py
        elif [ "${{ github.event.inputs.run_mode }}" == "stock_comparison" ]; then
          pytest pytestAssignmentGoogleFinance/test_stockComparison.py

      env:
        DISPLAY: ":99.0"

    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./test-reports/

